version:          '3'

services:
  ngx-web:
    image:        ngxp/ngx-stack
    ports:
      - 8080:8080
    environment:
      - API_BASE_URL=http://localhost:8080
      - INITDB=true
      - MIGRATEDB=true
      - MONGODB_URL=mongodb://ngx-db:27017/ngx-plus
    links:
      - ngx-db
    depends_on:
      - ngx-db
  ngx-db:
    image:        mongo
